### ISSUE TITLE
Generated docs are incomplete

### ISSUE THREAD

**Issue by ratbag98** [lukascobbler/basic_trie#1]
Running `cargo doc` basically just pretty-prints the contents of lib.rs along with the two type aliases. Modules, functions, structs etc. are not extracted into the sidebar. Clicking on the type aliases doesn't do anything useful.

I see you've created plenty of docs in the source, but they aren't visible except by reading the source.

**Comment by lukascobbler** [comment]
This is a rustdoc issue, as we already discussed on Reddit. I'm closing the issue for now as it is established this is not a crate-specific problem.

**Comment by lukascobbler** [comment]
The bug is now fixed in the newest version as I did some redesigning.
